# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/zrg/FPGA/Projects/LearningProjects/17_pingpong/17_pingpong.srcs/sources_1/ip/pong/pong.xci
# IP: The module: 'pong' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zrg/FPGA/Projects/LearningProjects/17_pingpong/17_pingpong.srcs/sources_1/ip/pong/pong_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pong'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/zrg/FPGA/Projects/LearningProjects/17_pingpong/17_pingpong.srcs/sources_1/ip/pong/pong.xci
# IP: The module: 'pong' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zrg/FPGA/Projects/LearningProjects/17_pingpong/17_pingpong.srcs/sources_1/ip/pong/pong_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pong'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
