# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM.xci
# IP: The module: 'MMCM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM.xci
# IP: The module: 'MMCM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/Xilinx_FPGA/Project/25B_UART_RAM_TFT/UART_RAM_TFT.srcs/sources_1/ip/MMCM/MMCM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MMCM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
