# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL.xci
# IP: The module: 'VGA_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL.xci
# IP: The module: 'VGA_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Coding/Xilinx/Project/LearningProjects/VGA/VGA.srcs/sources_1/ip/VGA_PLL/VGA_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
